### ISSUE TITLE
注意：请确保用户名/./kube 文件夹下存在k8s的kubeconfig文件

### ISSUE THREAD

**Issue by vihoyau** [noovertime7/kubemanage#16]
这个地方，搞了很久搞不懂怎么玩。
报错，不管我怎么设置~/.kube里面的config配置
config          config.yaml     configBackUp    kubeconfig
应该如何配置呢？

**Comment by noovertime7** [comment]
config.yaml是这个项目的配置文件，在kube目录下的是k8s的配置文件，因为当前版本是需要用k8s的config文件连接集群的，后面会重构这一部分

**Comment by noovertime7** [comment]
请问是找不到config.yaml吗，可以设置环境变量来定义配置文件所在位置

**Comment by vihoyau** [comment]
你好，加载还是会报错呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月1日(星期天) 晚上11:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [noovertime7/kubemanage] 注意：请确保用户名/./kube 文件夹下存在k8s的kubeconfig文件 (Issue #16)





 
请问是找不到config.yaml吗，可以设置环境变量来定义配置文件所在位置

**Comment by noovertime7** [comment]
麻烦把报错日志发一下吧

**Comment by noovertime7** [comment]
issue 超时关闭
