### ISSUE TITLE
始终无法指定kubeconfig

### ISSUE THREAD

**Issue by zhaohaihang** [noovertime7/kubemanage#22]
您好，我期望通过参数--kubeconfig 指定 kubeconfig文件的路径，但是始终提示错误，内容如下：
```
[root@localhost kubemanage]# ./main --kubeconfig "/root/.kube/config"
Error: unknown flag: --kubeconfig
Usage:
  kubemanage-server [flags]

Flags:
      --configFile string   The location of the kubemanage configuration file
  -h, --help                help for kubemanage-server
```
似乎是cobra 库，拦截了该参数。对于此问题您有什么好的建议吗？ 

顺便问一下，您为什么在kubemanage/pkg/core/kubemanage/v1/kube/init.go #31，处使用flag呢，而不是使用cobra，是出于什么原因考虑的？

**Comment by noovertime7** [comment]
历史原因，我这部分都重构完成了，新版本将使用agent操作k8s，最近太忙啦，还没更新到github :sparkles: @zhaohaihang

**Comment by zhaohaihang** [comment]
>


> 历史原因，我这部分都重构完成了，新版本将使用agent操作k8s，最近太忙啦，还没更新到github ✨ @zhaohaihang

感谢您的解答，期待新版本。请问您是否有交流群，我也想加入该项目
